#X-Generator: crowdin.com
# Content-related messages

content.content_missing=Falta el contingut del node\: \nnode\: {0}\nLector\: {1} \nSi us plau, contacteu amb l''administrador del sistema.
content.runtime_exec.property_moved=The property ''errorCodes'' has moved down onto the RuntimeExec class

index.recovery.out_of_date=Els \u00edndexs no estan sincronitzats amb la base de dades.
index.tracking.starting=\u00cdndex de recuperaci\u00f3 iniciat.
index.tracking.complete=\u00cdndex de recuperaci\u00f3 completat.
index.tracking.progress=\ Processament de transaccions als voltants {0}.
index.recovery.starting=\u00cdndex de recuperaci\u00f3 iniciat\: {0} transaccions.
index.recovery.complete=\u00cdndex de recuperaci\u00f3 completat.
index.recovery.progress=\ {0} % completat.
index.recovery.terminated=\u00cdndex de recuperaci\u00f3 ha finalitzat.

node.archive.msg.busy=Una purga o operaci\u00f3 de restauraci\u00f3 est\u00e0 actualment en curs

content.http_reader.err.no_connection=Incapa\u00e7 de connectar al servidor remot Alfresco mitjan\u00e7ant HTTP\: {0}
content.http_reader.err.no_authentication=El lector HTTP  ha set incapa\u00e7 d''autenticar al servidor remot\: {0}   
content.http_reader.err.check_cluster=Assegureu-vos que ''replicateUpdates'' i ''replicateUpdatesViaCopy'' estan habilitades per a la cache ''org.alfresco.cache.ticketsCache''.  Comproveu que la configuraci\u00f3 general del cl\u00faster \u00e9s correcta i est\u00e0 en funcionament.
content.http_reader.err.unrecognized=S''ha produ\u00eft un error no reconegut quan intentant descarregar el contingut del servidor remot\: servidor\: {0}\ncontingut \: {1} \nResposta HTTP\: {2}

metadata.extraction.err.type_conversion=Ha fallat l''extracci\u00f3 de les metadades perqu\u00e8 un valor extret no s''ha pogut convertir al tipus requerit\:\nExtractor\: {0}\nPropietat QName seleccionada\: {1}\nTipus requerit\: {2}\nValor Extret\: {3}

transform.err.format_or_password=No s''ha pogut convertir el contingut, possiblement a causa d''un fitxer formatat de forma incorrecte o protegit per contrasenya.

content.routing.err.invalid_default_store=El ''defaultStoreName'', ''{0}'' no fa refer\u00e8ncia a un magatzem de ''storesByName'' ({1}).
