#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Failed to authenticate, authenticator with name, {0}, not found
authentication.err.validation.authenticator.notactive=Authenticator \u0938\u0915\u094d\u0930\u093f\u092f \u0928\u0939\u0940\u0902 \u0939\u0948

authentication.err.authentication=Failed to authenticate, username or password is wrong. User name\:{0} Reason {1}
authentication.err.connection=Failed to connect to {0}. Reason {1}
authentication.err.communication=Failed to communicate with {0}. Reason {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Failed to connect, the ldap host {0} is unknown
authentication.err.connection.ldap.user.notfound=LDAP \u0909\u092a\u092f\u094b\u0917\u0915\u0930\u094d\u0924\u093e {0} \u0928\u0939\u0940\u0902 \u092e\u093f\u0932\u093e
authentication.err.connection.ldap.manager.notfound=LDAP \u092a\u094d\u0930\u092c\u0902\u0927\u0915 \u0909\u092a\u092f\u094b\u0917\u0915\u0930\u094d\u0924\u093e {0} \u0928\u0939\u0940\u0902 \u092e\u093f\u0932\u093e
authentication.err.connection.ldap.search=LDAP \u0916\u094b\u091c \u0915\u0930\u0928\u0947 \u092e\u0947\u0902 \u0905\u0938\u092e\u0930\u094d\u0925\u0964 \u0915\u093e\u0930\u0923 {0}

# PASSTHRU
authentication.err.connection.passthru.server=Passthru \u0938\u0930\u094d\u0935\u0930 \u0938\u0947 \u0938\u0924\u094d\u0930 \u0916\u094b\u0932\u0928\u0947 \u092e\u0947\u0902 \u0935\u093f\u092b\u0932 \u0930\u0939\u093e
authentication.err.passthru.token.unsupported=Unsupported authentication token type
authentication.err.passthru.guest.notenabled=Guest logons disabled
authentication.err.passthru.user.disabled=\u0905\u0915\u094d\u0937\u092e \u0916\u093e\u0924\u093e
authentication.err.passthru.user.notfound=Passthru user {0} not found

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validation of request
authentication.step.ldap.connecting=Connecting to LDAP Server {0} 
authentication.step.ldap.connected=Connected to LDAP server {0} with principal\: {1}
authentication.step.ldap.lookup=Lookup Test User userId\:{0} with query\: {1}
authentication.step.ldap.lookedup=Looked up Test User userId\:{0}, found distinguished name (DN)\:{1}
authentication.step.ldap.format.user=User Name Format specified, userNameFormat\:{2} Format user userId\:{0} to make Distinguished name (DN)\:{1}
authentication.step.ldap.authentication=UserId \u0915\u094b \u092a\u094d\u0930\u092e\u093e\u0923\u093f\u0924\: {0}


# Sync Summary message 
synchronization.summary.status={0} user(s) and {1} group(s) processed


# Error messages
authentication.ldap.validation.authenticator.notfound=Authenticator not found

# Synchronization Diagnostic Steps
synchronization.step.users=Found {0} users
synchronization.step.groups=Found {0} groups
synchronization.step.users.lastsynced=Users last successfully synced {0}
synchronization.step.groups.lastsynced=Groups last successfully synced {0}

synchronization.err.ldap.search=Error during LDAP Search. Reason\:{0}
synchronization.err.ldap.get.user.id.missing=User missing user id attribute DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Group missing group id attribute DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Invalid search base {0} reason\: {1}

synchronization.err.ldap.group.member.missing.exception="Failed to resolve member of group {0} with distinguished name\: {1}, reason {2});
synchronization.err.ldap.group.member.missing="Failed to resolve member of group {0} with distinguished name\: {1});








