#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Fejlede ved autentificering, autentificering med navn, {0}, blev ikke fundet
authentication.err.validation.authenticator.notactive=Godkenderen er ikke aktiv

authentication.err.authentication=Kunne ikke logge dig ind, fordi enten brugernavnet eller adgangskoden er forkert. Brugernavn\: {0}, \u00e5rsag\: {1}
authentication.err.connection=Der kunne ikke oprettes forbindelse til {0}. \u00c5rsag {1}
authentication.err.communication=Der kunne ikke kommunikere med {0}. \u00c5rsag\: {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Der kunne ikke oprettes forbindelse, LDAP-v\u00e6rt {0} er ukendt
authentication.err.connection.ldap.user.notfound=LDAP-brugeren {0} blev ikke fundet
authentication.err.connection.ldap.manager.notfound=LDAP-Administrator {0} blev ikke fundet
authentication.err.connection.ldap.search=Ikke i stand til at s\u00f8ge i LDAP. \u00c5rsag\: {0}

# PASSTHRU
authentication.err.connection.passthru.server=Kunne ikke \u00e5bne session til gennemgangsserver
authentication.err.passthru.token.unsupported=Ikke-underst\u00f8ttet godkendelsestype for token 
authentication.err.passthru.guest.notenabled=G\u00e6stelogin deaktiveret
authentication.err.passthru.user.disabled=Konto deaktiveret
authentication.err.passthru.user.notfound=Gennemgangsbrugeren {0} blev ikke fundet

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validering af foresp\u00f8rgsel
authentication.step.ldap.connecting=Opretter forbindelse til LDAP serveren {0} 
authentication.step.ldap.connected=Forbindelse til LDAP-serveren {0} med principal\: {1}
authentication.step.ldap.lookup=Find testbruger brugerId\: {0} med foresp\u00f8rgsel\: {1}
authentication.step.ldap.lookedup=S\u00f8gte efter testbruger brugerId\: {0}, fandt entydigt navn (DN)\: {1}
authentication.step.ldap.format.user=Brugernavnsformat angivet, userNameFormat\: {2}. Formater brugerens brugerid\: {0} for at benytte et entydigt navn (DN)\: {1}
authentication.step.ldap.authentication=Godkend brugerId\: {0}


# Sync Summary message 
synchronization.summary.status={0} bruger(e) og {1} gruppe(r) gennemf\u00f8rt


# Error messages
authentication.ldap.validation.authenticator.notfound=Godkenderen blev ikke fundet

# Synchronization Diagnostic Steps
synchronization.step.users=Fandt {0} brugere
synchronization.step.groups=Fandt {0} grupper
synchronization.step.users.lastsynced=Brugere seneste succesfulde synkronisering {0}
synchronization.step.groups.lastsynced=Gruppens seneste succesfulde synkronisering {0}

synchronization.err.ldap.search=Fejl under LDAP-s\u00f8gning. \u00c5rsag\: {0}
synchronization.err.ldap.get.user.id.missing=Bruger mangler brugerid-attribut DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Gruppen mangler gruppeid-attribut DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Ugyldigt udgangspunkt for s\u00f8gning {0} \u00e5rsag\: {1}

synchronization.err.ldap.group.member.missing.exception="Fejlede i fors\u00f8get p\u00e5 at gendanne medlem af gruppe {0} med det entydige navn\: {1}, \u00e5rsag {2});
synchronization.err.ldap.group.member.missing="Fejlede i fors\u00f8get p\u00e5 at genskabe medlem af gruppe {0} med entydige navn\: {1});








